### PR TITLE
Add provisional integration for ical2org and mu4e/GNUS

### PR DESCRIPTION
**Pull request by swflint**
This provides an example for integration between ical2org and two different mailers (currently GNUS and mu4e).  Neither is well tested, and this needs more documentation, but hopefully this provides a good example and some inspiration to others for implementation.

### CODE REVIEW

**Comment by rjhorniii** [comment]
Thanks I'll take a look.

I like to have test cases but it might be impractical for this.

**Comment by swflint** [comment]
Cool.  Yeah, given how it's built, it might be.

I'm also going to be looking at possibly writing a systemd-user service/timer file -- thoughts?

**Comment by rjhorniii** [comment]
The README has examples for a systemd/time usage (and mu4e attachment processing).  Is the idea to make them into files as part of the distribution?  I wasn't sure that was such a good idea.  They need editing before they are useful.  I was assuming people could cut and paste from the README and then customize.

**Comment by swflint** [comment]
If you notice, the implementation is semi-parameterizable.  And as for the systemd/time usage, I do agree that they likely need to be edited, but perhaps an integrationExamples directory would be more appropriate?

**Pull request closed without merging**
